# Generated by Django 4.1.4 on 2022-12-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_uuid',
        ),
    ]
